---
stripLength: 60

schedule:
  - state: ON
    start: [17, 0]
    end: [23, 0]

dudes:
  - rgb: [255, 25, 0]
  - rgb: [180, 40, 0]
  #- strobe: true
  #  blendMode: REPLACE
  #  power: 12
  #  width: 10
  #  speed: 20
  #  scale: 5
  #  offset: -4
  #  rgb: [30, 120, 255]
  - constant: true
    blendMode: DEFAULT
    rgb: [12, 0, 16]
