---
ledType: dotstar
stripLength: 120

schedule:
  - state: ON
    start: [17, 0]
    end: [23, 0]

dudes:
  - rgb: [255, 25, 0]
  - rgb: [180, 40, 0]
#  - strobe: true
#    blendMode: REPLACE
#    power: 2
#    speed: 20
#    rgb: [30, 120, 255]
  - mode: constant
    blendMode: DEFAULT
    rgb: [40, 0, 60]
