---
ledType: dotstar
stripLength: 120

schedule:
  - state: ON
    start: [17, 0]
    end: [23, 0]

dudes:
  - rgb: [5, 20, 255]
    width: 50
    mode: stripes
  - rgb: [130, 130, 115]
    width: 50
    offset: 50
    mode: stripes
