---
ledType: dotstar
stripLength: 120

schedule:
  - state: ON
    start: [17, 0]
    end: [23, 0]

dudes:
  - rgb: [160, 0, 0]
  - rgb: [0, 0, 120]
    linked: true
    slide: 1
  - mode: constant
    blendMode: DEFAULT
    rgb: [30, 30, 30]
